[package]
name = "geotiff2stl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.3", features = ["derive"] }
stl_io = "0.7.0"
gdal = { version = "0.15.0", features = [] }
