name: ci
on: [push, pull_request]
jobs:
  cargo-check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/46bit/geotiff2stl-base:latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v3
      - run: cargo check

  cargo-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/46bit/geotiff2stl-base:latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v3
      - run: cargo test

  cargo-fmt:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/46bit/geotiff2stl-base:latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: rustup component add rustfmt
      - uses: actions/checkout@v3
      - run: cargo fmt --all -- --check

  cargo-clippy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/46bit/geotiff2stl-base:latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: rustup component add clippy
      - uses: actions/checkout@v3
      - run: cargo clippy -- -D warnings

  cargo-build-release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/46bit/geotiff2stl-base:latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v3
      - run: cargo build --release
